_target_: cgdit.prop_models.tc_classifier.DiffusionBackboneBinaryClassifier

target_prop: ${data.prop}
target_mean: 0.0
target_std: 1.0
pretrained_model_path: null
pos_weight: 1.0
time_dim: 256

decoder:
  _target_: cgdit.pl_modules.decoder.cspnet.CSPNet
  hidden_dim: 512
  latent_dim: 256
  max_atoms: 100
  num_layers: 6
  act_fn: silu
  dis_emb: sin
  num_freqs: 128
  edge_style: fc
  max_neighbors: 20
  cutoff: 7.0
  ln: true
  ip: true
  pred_type: true
  pred_scalar: true
  pooling: mean
