_target_: cgdit.pl_modules.diffusion.Diffusion
time_dim: 256
latent_dim: 0
cost_coord: 1.
cost_lattice: 1.
cost_atom: 1.
max_neighbors: 20  # maximum number of neighbors for OTF graph bulding in decoder
radius: 7.  # maximum search radius for OTF graph building in decoder
timesteps: 1000

cond_dropout_prob: 0.1
conditions:
  formation_energy_per_atom:
    type: scalar
    scale: 1.029374   # 必须填：数据集该属性的标准差 (std)
    shift: -1.219803  # 必须填：数据集该属性的均值 (mean)

#  e_above_hull:
#    type: scalar
#    scale: 0.023265
#    shift: 0.017478

#  band_gap:
#    type: scalar
#    scale: 1.417749
#    shift: 0.791848

#  spacegroup:
#    type: categorical
#    num_classes: 230 # 1-230

defaults:
  - decoder: cspnet
  - beta_scheduler: cosine
  - sigma_scheduler: wrapped
  - d3pm_scheduler: d3pm